### ISSUE TITLE
Markdown is being parsed in sent messages

### ISSUE THREAD

**Issue by Dinoguy1000** [jaydenkieran/mw-discord#13]
![image](https://user-images.githubusercontent.com/818183/60376538-4b2f8500-99d5-11e9-81a6-0f53432197e6.png)
[diff](https://yugipedia.com/index.php?title=MediaWiki:Gadget-MarkupFormatting.js&diff=prev&oldid=4121726)

**Comment by Dinoguy1000** [comment]
A more egregious case: 
![image](https://user-images.githubusercontent.com/818183/61751513-347b1480-ad6e-11e9-9fc5-1d122601e088.png)
[diff](https://yugipedia.com/index.php?title=Paradox_Brothers:_Guardians_of_the_Gate&diff=prev&oldid=4135565)

**Comment by Xkeeper0** [comment]
This looks like it's still an issue in the most recent version of the repository, and the pull request that fixed it seems to have been closed without merge.

Is this repo still being maintained? If so I can try recreating the fix and making a PR.

**Comment by jaydenkieran** [comment]
@Xkeeper0 This repo is still maintained but the person who made that PR deleted their GitHub account unfortunately.
