### ISSUE TITLE
Markdown in page names is parsed

### ISSUE THREAD

**Issue by Dinoguy1000** [jaydenkieran/mw-discord#15]
Related to #13. Presumably this would also affect usernames.
![image](https://user-images.githubusercontent.com/818183/61839700-30c1bd80-ae54-11e9-8c1d-f378698955bd.png)
[page](https://yugipedia.com/index.php?title=The_Winged_Dragon_of_Ra_*Battle_Mode*_(ROD)&redirect=no)

**Comment by Dinoguy1000** [comment]
Slightly weirder example:
![image](https://user-images.githubusercontent.com/818183/61839862-cc532e00-ae54-11e9-9065-6d455ea984da.png)
[page](https://yugipedia.com/index.php?title=The_Winged_Dragon_of_Ra**Sphere_Mode*_(ROD)&redirect=no)

**Comment by jaydenkieran** [comment]
Closing in favour of #13
