### ISSUE TITLE
PHP Notice: Undefined variable: wgDiscordUseFileGetContents

### ISSUE THREAD

**Issue by MPThLee** [jaydenkieran/mw-discord#18]
Discord/src/Utils.php in handleError at line 81

I think it need to use a "is_set" function first.

**Comment by jaydenkieran** [comment]
Should be fixed by https://github.com/jaydenkieran/mw-discord/commit/47eef3c35d3d4810c2237c1c3873e9e7005f5c56 - can you try updating the extension?
