### ISSUE TITLE
Different emoji for page creations

### ISSUE THREAD

**Issue by Dinoguy1000** [jaydenkieran/mw-discord#25]
Currently page creations use the pencil emoji, the same as non-creation edits. For quick visual distinction, it would be useful for them to use a different emoji, though I don't have any suggestions for a new one.

**Comment by jaydenkieran** [comment]
It’d probably be good to have the emojis be user-configurable, but it was just a neat little thing I added in last night alongside the other feature requests

**Comment by Dinoguy1000** [comment]
> It’d probably be good to have the emojis be user-configurable
Funny you should mention that, I've been thinking about exactly that for the past however many hours. I can't decide how it would make sense to do this though (configuration variables, MW messages, etc).

**Comment by jaydenkieran** [comment]
Perhaps configurable in the same way that permissions are configurable in core MediaWiki, using a simple array.

e.g `$wgDiscordEmojis['PageContentSaveComplete'] = ':notepad:';`

**Comment by Dinoguy1000** [comment]
That would work for me.
