### ISSUE TITLE
Creation protection/salting isn't shown

### ISSUE THREAD

**Issue by Dinoguy1000** [jaydenkieran/mw-discord#28]
Per title.

**Comment by jaydenkieran** [comment]
No hook supports this, and when a title is protected, there is [no hook](https://gerrit.wikimedia.org/g/mediawiki/core/+/master/includes/page/WikiPage.php#2619). So this is probably going to be a 'wontfix' for the time being. If we start tracking *log entries* and using that to send the Discord notifications instead, this will probably become more possible.
