### ISSUE TITLE
Investigate using RequestContext.php in place of $wgUser

### ISSUE THREAD

**Issue by Dinoguy1000** [jaydenkieran/mw-discord#9]
~~In src/DiscordHooks.php, some functions require a `$user` parameter to be passed in, whereas others use the `$wgUser` global. This is inconsistent and potentially a source of errors (e.g. I almost didn't notice the discrepancy in #8 ). If there's a functional difference between these, it needs to be clearly documented.~~

There might be places where [RequestContext.php](https://www.mediawiki.org/wiki/Manual:RequestContext.php) could be used instead of the current `$wgUser`.

**Comment by jaydenkieran** [comment]
The reason some of the hooks use `$wgUser` is because the hook itself does not pass the User object associated with that specific action, so we have to fall back to the global variable. It's not pretty, but there's not really much else we can do about it.

**Comment by Dinoguy1000** [comment]
Another reason to do this is because [`$wgUser` is going away](https://phabricator.wikimedia.org/T159299).
